#############################################################################
# Makefile for building: DFM2QT4
# Generated by qmake (2.01a) (Qt 4.8.4) on: Fri Mar 22 13:15:25 2013
# Project:  DFM2QT4.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile DFM2QT4.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -D_REENTRANT -Wall -W $(DEFINES)
CXXFLAGS      = -m64 -pipe -Wunused-parameter -O2 -D_REENTRANT -Wall -W $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/default -I. -I/usr/include/QtDesigner -I/usr/include/QtUiTools -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include/QtXml -I/usr/include -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib64 -L/usr/lib64 -L/usr/X11R6/lib64 -lQtUiTools -lQtXml -lQtGui -lQtCore -lpthread -lQtDesigner 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		cdfm2guitree.cpp \
		cguitree2ui.cpp \
		cuidomdocument.cpp \
		cguitreedomdocument.cpp \
		cuidomelement.cpp \
		cguitreedomelement.cpp \
		clogger.cpp \
		formpreview.cpp \
		cfrontend2.cpp moc_cdfm2guitree.cpp \
		moc_cguitree2ui.cpp \
		moc_clogger.cpp \
		moc_formpreview.cpp \
		moc_cfrontend2.cpp
OBJECTS       = main.o \
		cdfm2guitree.o \
		cguitree2ui.o \
		cuidomdocument.o \
		cguitreedomdocument.o \
		cuidomelement.o \
		cguitreedomelement.o \
		clogger.o \
		formpreview.o \
		cfrontend2.o \
		moc_cdfm2guitree.o \
		moc_cguitree2ui.o \
		moc_clogger.o \
		moc_formpreview.o \
		moc_cfrontend2.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/uitools.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/designer.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		DFM2QT4.pro
QMAKE_TARGET  = DFM2QT4
DESTDIR       = 
TARGET        = DFM2QT4

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_formpreview.h ui_cfrontend2.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: DFM2QT4.pro  /usr/share/qt4/mkspecs/default/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/uitools.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/designer.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib64/libQtXml.prl \
		/usr/lib64/libQtCore.prl \
		/usr/lib64/libQtGui.prl \
		/usr/lib64/libQtUiTools.prl \
		/usr/lib64/libQtDesigner.prl
	$(QMAKE) -o Makefile DFM2QT4.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/uitools.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/designer.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib64/libQtXml.prl:
/usr/lib64/libQtCore.prl:
/usr/lib64/libQtGui.prl:
/usr/lib64/libQtUiTools.prl:
/usr/lib64/libQtDesigner.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile DFM2QT4.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/DFM2QT41.0.0 || $(MKDIR) .tmp/DFM2QT41.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/DFM2QT41.0.0/ && $(COPY_FILE) --parents cdfm2guitree.h cguitree2ui.h cuidomdocument.h cguitreedomdocument.h cuidomelement.h cguitreedomelement.h clogger.h formpreview.h cfrontend2.h .tmp/DFM2QT41.0.0/ && $(COPY_FILE) --parents main.cpp cdfm2guitree.cpp cguitree2ui.cpp cuidomdocument.cpp cguitreedomdocument.cpp cuidomelement.cpp cguitreedomelement.cpp clogger.cpp formpreview.cpp cfrontend2.cpp .tmp/DFM2QT41.0.0/ && $(COPY_FILE) --parents formpreview.ui cfrontend2.ui .tmp/DFM2QT41.0.0/ && (cd `dirname .tmp/DFM2QT41.0.0` && $(TAR) DFM2QT41.0.0.tar DFM2QT41.0.0 && $(COMPRESS) DFM2QT41.0.0.tar) && $(MOVE) `dirname .tmp/DFM2QT41.0.0`/DFM2QT41.0.0.tar.gz . && $(DEL_FILE) -r .tmp/DFM2QT41.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_cdfm2guitree.cpp moc_cguitree2ui.cpp moc_clogger.cpp moc_formpreview.cpp moc_cfrontend2.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_cdfm2guitree.cpp moc_cguitree2ui.cpp moc_clogger.cpp moc_formpreview.cpp moc_cfrontend2.cpp
moc_cdfm2guitree.cpp: cguitreedomdocument.h \
		cguitreedomelement.h \
		cdfm2guitree.h
	/usr/bin/moc $(DEFINES) $(INCPATH) cdfm2guitree.h -o moc_cdfm2guitree.cpp

moc_cguitree2ui.cpp: cuidomdocument.h \
		cuidomelement.h \
		cguitreedomdocument.h \
		cguitreedomelement.h \
		cguitree2ui.h
	/usr/bin/moc $(DEFINES) $(INCPATH) cguitree2ui.h -o moc_cguitree2ui.cpp

moc_clogger.cpp: clogger.h
	/usr/bin/moc $(DEFINES) $(INCPATH) clogger.h -o moc_clogger.cpp

moc_formpreview.cpp: formpreview.h
	/usr/bin/moc $(DEFINES) $(INCPATH) formpreview.h -o moc_formpreview.cpp

moc_cfrontend2.cpp: formpreview.h \
		cfrontend2.h
	/usr/bin/moc $(DEFINES) $(INCPATH) cfrontend2.h -o moc_cfrontend2.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_formpreview.h ui_cfrontend2.h
compiler_uic_clean:
	-$(DEL_FILE) ui_formpreview.h ui_cfrontend2.h
ui_formpreview.h: formpreview.ui
	/usr/bin/uic formpreview.ui -o ui_formpreview.h

ui_cfrontend2.h: cfrontend2.ui \
		clogger.h
	/usr/bin/uic cfrontend2.ui -o ui_cfrontend2.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp cfrontend2.h \
		formpreview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

cdfm2guitree.o: cdfm2guitree.cpp cdfm2guitree.h \
		cguitreedomdocument.h \
		cguitreedomelement.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cdfm2guitree.o cdfm2guitree.cpp

cguitree2ui.o: cguitree2ui.cpp cguitree2ui.h \
		cuidomdocument.h \
		cuidomelement.h \
		cguitreedomdocument.h \
		cguitreedomelement.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cguitree2ui.o cguitree2ui.cpp

cuidomdocument.o: cuidomdocument.cpp cuidomdocument.h \
		cuidomelement.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cuidomdocument.o cuidomdocument.cpp

cguitreedomdocument.o: cguitreedomdocument.cpp cguitreedomdocument.h \
		cguitreedomelement.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cguitreedomdocument.o cguitreedomdocument.cpp

cuidomelement.o: cuidomelement.cpp cuidomelement.h \
		cuidomdocument.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cuidomelement.o cuidomelement.cpp

cguitreedomelement.o: cguitreedomelement.cpp cguitreedomelement.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cguitreedomelement.o cguitreedomelement.cpp

clogger.o: clogger.cpp clogger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o clogger.o clogger.cpp

formpreview.o: formpreview.cpp formpreview.h \
		ui_formpreview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o formpreview.o formpreview.cpp

cfrontend2.o: cfrontend2.cpp cfrontend2.h \
		formpreview.h \
		ui_cfrontend2.h \
		cdfm2guitree.h \
		cguitreedomdocument.h \
		cguitreedomelement.h \
		cguitree2ui.h \
		cuidomdocument.h \
		cuidomelement.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cfrontend2.o cfrontend2.cpp

moc_cdfm2guitree.o: moc_cdfm2guitree.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cdfm2guitree.o moc_cdfm2guitree.cpp

moc_cguitree2ui.o: moc_cguitree2ui.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cguitree2ui.o moc_cguitree2ui.cpp

moc_clogger.o: moc_clogger.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_clogger.o moc_clogger.cpp

moc_formpreview.o: moc_formpreview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_formpreview.o moc_formpreview.cpp

moc_cfrontend2.o: moc_cfrontend2.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cfrontend2.o moc_cfrontend2.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

